apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: nsapp
  labels:
    app: employees
    owner: Rushi
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: 907620523525.dkr.ecr.us-east-1.amazonaws.com/webapp:latestv0.1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: "mysql.nsmysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: password
        - name: APP_COLOR
          value: "lime"
